from transformers import pipeline
from random import randrange

# load model and tokenizer from huggingface hub with pipeline
summarizer = pipeline("summarization", model="philschmid/flan-t5-base-samsum", do_sample=True, temperature = 1.8)

# select a random test sample

#transcript_content = [
sample=		"""SPEAKER_01 : HEY, HAVE YOU EVER TRIED THAT NEW SUSHI PLACE DOWNTOWN?"
		"SPEAKER_00 : OH, YOU MEAN SUSHI FUSION? YEAH, I WENT THERE LAST WEEK. THE FOOD IS AMAZING!"
		"SPEAKER_01 : REALLY? WHAT DID YOU ORDER?"
		"SPEAKER_00 : I HAD THE SPICY TUNA ROLL AND THEIR SIGNATURE DRAGON ROLL. BOTH WERE SO GOOD!"
		"SPEAKER_01 : NICE! DO THEY HAVE ANY GOOD VEGETARIAN OPTIONS? I'M TRYING TO CUT BACK ON MEAT LATELY."
		"SPEAKER_00 : DEFINITELY. THEY HAVE A VEGETARIAN COMBO PLATTER AND A REALLY GOOD AVOCADO ROLL."
		"SPEAKER_01 : THAT SOUNDS PERFECT. HOW'S THE AMBIANCE THERE?"
		"SPEAKER_00 : IT'S REALLY COZY AND MODERN, BUT NOT TOO FANCY. GREAT PLACE TO RELAX AND ENJOY A MEAL."
		"SPEAKER_01 : I THINK I'LL CHECK IT OUT THIS WEEKEND. THANKS FOR THE RECOMMENDATION!"
		"SPEAKER_00 : NO PROBLEM! LET ME KNOW WHAT YOU THINK WHEN YOU GO!""" #]

lst = ['SPEAKER_00 : E', 'SPEAKER_01 : ARIA HOW ARE YOU', 'SPEAKER_00 : HEY I AM GOOD WHAT ABOUT YOU', 'SPEAKER_01 : I AM ALSO FINE', 'SPEAKER_00 : AFTER A VERY LONG TIME WE ARE MEETING', "SPEAKER_01 : YES IT'S A VERY LONG TIME I MISSED YOU SO MUCH", 'SPEAKER_00 : ME TOO DUE TO OFFICE WORK I WAS VERY MUCH BUSSY', 'SPEAKER_01 : DER I NO I WAS ALSO VERY MUCH INVOLVED IN MY RESEARCH FOR', 'SPEAKER_00 : BUT AT LAST WE BOTH GET TIME FOR EACH OTHER', "SPEAKER_01 : YES SO LET'S GO TO THIS RESTAURANT", "SPEAKER_00 : YES I AM VERY MUCH HUNGRY HAVE A TALK WELL EATING LET'S GO", 'SPEAKER_01 : YES', 'SPEAKER_00 : LIKE SHARE SUBSCRIBE PLEASE']

def concatenate(lst):
    s = ''
    for i in lst:
        s+=i + '\n'
    return s

print("c:",concatenate(lst))

print(f"dialogue: \n{sample}\n---------------")

# summarize dialogue
res = summarizer(concatenate(lst))

print(f"flan-t5-base summary:\n{res[0]['summary_text']}")